guide/billable-metrics/dimensions.mdx
Improve Dashboard section of billable metric > dimension
=> doc(Dimension): improve dashboard guide

api-reference/billable-metrics/destroy.mdx, api-reference/taxes/create.mdx, api-reference/taxes/destroy.mdx, api-reference/taxes/get-all.mdx, api-reference/taxes/get-specific.mdx, api-reference/taxes/object.mdx, api-reference/taxes/tax-object.mdx, api-reference/taxes/update.mdx, guide/customers/customer-management.mdx, guide/invoicing/download-invoices.mdx, guide/invoicing/fees.mdx, guide/invoicing/grace-period.mdx, lago-openapi.yaml, mint.json
Add taxes in other section of the guide
=> doc(taxes): add taxes info in other section

api-reference/fees/fee-object.mdx
Add field description to Fees object
=> doc(Fees): update field description

guide/lago-open-api.mdx
Swagger link was broken, just fixed it
=> doc(openAPI): fix and edit swagger link

lago-openapi.yaml
Add `tax_codes` to create plans
=> doc(Plan): Add taxes to create plan

api-reference/resources/locales.mdx
Update the pdf template and code snippet of Locales
=> doc(Locales): improve doc template

api-reference/resources/locales.mdx
Improve Locale json readability
=> doc(Locale): improve json readability

api-reference/resources/locales.mdx
Restructure the local template with double quotes and correct spacing
=> doc(Locale): add double quotes to all values

api-reference/webhooks/format---signature.mdx
Edit python snippet for `Decoding and validating webhook HMAC signature`.
Thanks Tiangan for reporting it.
=> doc(Webhook): Edit hmac signature phython snippet

api-reference/resources/locales.mdx
Add old versions translation to locales payload
=> doc(Locales): add old versions tranllation in payload

api-reference/webhooks/messages.mdx
Add webhook documentation when subscription undergoes an upgrade or a downgrade
=> doc(Webhook): Add doc subscription upgrade downgrade webhook

integrations/payments/adyen-integration.mdx, integrations/payments/gocardless-integration.mdx, integrations/payments/stripe-integration.mdx
User is able to define a redirect url after a PSP checkout, here's the documentation related to this new feature
=> doc(PSP): add redirect url doc

guide/emails.mdx
Remove space between element when adding several emails
=> doc(emails): remove space from different email

guide/invoicing/grace-period.mdx
Add documentation regarding `Edit fee on a draft invoice`
=> doc(Grace period): Add edit draft doc

integrations/payments/adyen-integration.mdx
Edit the expiration date info (from `70` to `69` days) when checkout_url is created for Adyen integration
=> doc(Integration): update checkout url adyen

api-reference/invoices/payment-url.mdx, api-reference/invoices/void.mdx, lago-openapi.yaml, mint.json
1/ Add missing endpoints :
- POST /invoices/{lago:id}/void
- POST /invoices/{lago:id}/payment_url
2/ Re-order all endpoints to follow the standard defined : `POST` / `PUT` / `DEL` / `GET`
3/ Update open api yaml file
=> doc(API Ref): add missing endpoints

guide/invoicing/overview.mdx
Update invoice numbering documentation to remove the reset at each end of month and adding invoice numbering generation at invoice finalization.
=> doc(Invoice): Numbering improvement

guide/migration/migration-to-v1.2.0.mdx
I updated the diff in the snippets. The diff looks weird here but here are some before/after screenshots.
=> Update guide snippets

api-reference/customers/object.mdx
Adding `shipping_address` object in API Customer object
=> doc(customer): Add shipping address in customer object

guide/self-hosted/docker.mdx
Fixes https://github.com/getlago/lago/issues/374
=> fix(docker): use correct env var for google sso

guide/subscriptions/upgrades-downgrades.mdx
In Guide>Subscription > Upgrade/Downgrade, payload was not accurate for sub_id.
=> doc(Subscription): Update api payload

guide/security/rbac.mdx
Add one-off invoice to finance role
=> doc(RBAC): Add one-off to finance role

integrations/introduction.mdx, integrations/taxes/anrok.mdx
Add reasons to have a failed taxed syncro
=> doc(Anrok): Add reason to failed  tax syncro

mint.json
Documentation becomes more and more crowded, the goal is to add more links (community, status…) but also in the meantime restructure the navigation
=> doc(Nav): Revamp doc navigation

guide/plans/charges/charge-models/dynamic.mdx
Add events payload example to highlight the notion of total amount
=> doc(Charges): Add event payload examples

guide/credit-notes.mdx
Here's the documentation linked to `Create credit note on prepaid credits invoices`
=> doc(Credit note): Add doc for prepaid credits

integrations/crm/hubspot.mdx
=> fix(hubspot): Fix a typo

api-reference/webhooks/format---signature.mdx
Adds a new PHP example for this section.
=> Add PHP example for HMAC signature

api-reference/webhooks/format---signature.mdx
=> fix: Replace api key to hmac key for webhooks

api-reference/wallets/get-specific-transaction.mdx, mint.json
Add new endpoint to get a specific wallet transaction
=> doc(Wallet): Add endpoint to retrieve a transaction

api-reference/webhooks/format---signature.mdx
also adding a note about retry
=> Add note about webhook unique key for idempotency

guide/invoicing/overview.mdx, guide/plans/charges/spending-minimum.mdx, guide/plans/commitment.mdx
When reading documentation for spending minimum and minimum commitment, I got confused at some sentences.
I added two important info:
- For spending minimum, it is only applied for in arrears
- For minimum commitment, it includes subscription fee and usage-based charges
=> rephrased sentences for spending minimum and minimum commitment

guide/wallet-and-prepaid-credits/wallet-top-up-and-void.mdx
Please find the doc mentioning the logic behind prepaid credit paid top-up rounding rules.
=> doc(Wallet): Add details on rounding rules

welcome.mdx
=> doc(Welcome): Fix welcome title

api-reference/resources/currencies.mdx
Related to https://github.com/getlago/lago-api/pull/3889, adding new `GHS` currency
=> misc(currency): Add Ghanaian Cedi (GHS) currency

tracking.js
added hs script:
```
<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/49109312.js"></script>
```
=> feat: add hs script

snippets/templates/create-customer.mdx, snippets/templates/create-subscription.mdx, snippets/templates/customer-usage.mdx, snippets/templates/setup-lago.mdx, templates/hybrid/segment.mdx, templates/introduction.mdx, templates/payg/algolia.mdx, templates/payg/bigquery.mdx, templates/per-seat/notion.mdx, templates/per-token/mistral.mdx, templates/per-token/openai.mdx, templates/per-transaction/stripe.mdx, tracking.js
- Added link to `lago-billing-examples` repo in Templates introduction page
- Refactored all Templates into:
- intro + video (if exists)
- step-by-step implementation with relevant data schema
- wrap up
Achieves brevity and quicker implementation
=> fix(Templates): refactor into easy steps

guide/payments/stripe-integration.mdx, integrations/payments/stripe-integration.mdx
Sorry my editor removes extra space at the end so there is a lot of "changes". make sure you review without whitespace.
See https://github.com/getlago/lago-api/pull/4336 for details.
=> note about payments requiring action with Stripe
