api-reference/plans/create.mdx, api-reference/subscriptions/assign-plan.mdx, api-reference/subscriptions/get-specific.mdx, api-reference/subscriptions/update.mdx, guide/subscriptions/assign-plan.mdx, guide/subscriptions/edit-subscription.mdx, lago-openapi.yaml, mint.json
Documentation regarding Overrides plan when creating a subscription.
It should impact the documentation guide (`assign a plan` & `edit a subscription`)
It should impact the API ref (`POST /subscription` & `PUT /subscription` & `POST /subscription/{external_id`)
+
Impact `POST /plans` with a correction regarding `lago_billable_metric_id` to `billable_metric_id`
=> doc(Subscription): Add overrides documentation & api ref

api-reference/resources/locales.mdx
Adding Spanish and Swedish in the list of document locales supported by Lago
=> doc(Locales): Add Spanish and Swedish in documentation

faq/about-software.mdx, guide/lago-open-api.mdx, integrations/crm/salesforce-crm.mdx
Hello guys 👋
It seems like Mintlify is transforming plain text urls into links. This is bad for SEO as we are linking to 404s.
In the future, could you try to put urls inside quotes to prevent this behaviour?
Thank you 🙌
=> fix 404s + missing s to http links

guide/payments/gocardless-integration.mdx
Hello team,
removing one last 404 link.
Bonus: the content was actually broken because the `{id}` part would not show up. See the screenshot attached.
=> Remove broken GoCardless link

faq/about-lago.mdx
previous link was pointing to PostHog, another open-source SaaS product.
=> Add correct link to Github Commit Activity

api-reference/events/batch.mdx
Documentation in this [page](https://docs.getlago.com/api-reference/events/batch) is outdated after this endpoint change https://github.com/getlago/lago-python-client/pull/219
=> Update outdated python client for Batch usage events

guide/subscriptions/assign-plan.mdx
Add `\` next to $ sign to avoid markdown style
=> doc(Subscription): Fix typo $ to \$

api-reference/subscriptions/terminate.mdx
Update from `customer_id` to `subscription.external_id` for go client
=> doc(Subscription): Correct typo on terminate sub

integrations/payments/adyen-integration.mdx
I had issues getting customers to be created automatically following the documentation. For some reason I had to enable _Recurring details_ within _Additional data_ to get it to work. I didn't seem to be receiving a `shopperReference` without it. This was on a newly created test account made a few days ago. I figured this out based on this [code](https://github.com/getlago/lago-api/blob/d42f2e48cbad9b87e45f116fd8df3e42214e4dd0/app/services/payment_provider_customers/adyen_service.rb#L101-L104).
Free feel to edit my copy - this was mostly for other persons who face the same issue. Thanks!
=> Add additional details for automatic adyen customer creation 

api-reference/events/batch.mdx, api-reference/events/usage.mdx
* The snippet to send one event was outdated (missing context, using wrong Properties type, wrong return from Create).
* The batch didn't have a snippet.
=> Update go snippets to send events

api-reference/webhooks/messages.mdx
👉 https://getlago.canny.io/feature-requests/p/regroup-invoices-to-generate-one-payment-intent
We want to be able to group invoices to generate one payment.
Today we don't track payment terms and do not mention whether a payment or an invoice is overdue.
The goal of this PR is to add the `payment_overdue` webhook.
=> feat(dunning): Add payment_overdue webhook message

api-reference/intro.mdx
In case you're self-hosting Lago, you also need to pass the API url.
---
=> misc(clients): Add custom url in intro snippets

guide/wallet-and-prepaid-credits/overview.mdx, guide/wallet-and-prepaid-credits/wallet-top-up-and-void.mdx
As we had the ability to define transaction_metadata at each manual or recurring top-up, here's the documentation that covers this experience.
=> doc(Wallet): Add metadata doc on transaction

guide/wallet-and-prepaid-credits/wallet-top-up-and-void.mdx
- **Branch Name:** `fix/void-credits-to-voided-credits`
- **Commit Message:** `Fixes Issue #394: void_credits to voided_credits`
- **Number of Commits:** 1
- **Test Status:** No errors
- **PR Title:** Fixes Issue #394: void_credits to voided_credits
- **Description:** This PR addresses Issue #394, where the variable `void_credits` was mistakenly used instead of `voided_credits`. The necessary corrections have been made across all relevant files to ensure consistent naming.
- **Issue Reference:** Closes #394
- **Labels:** `fix`, `bug`
=> Fixes Issue #394 : void_credits to voided_credits

guide/self-hosted/docker.mdx
Changes the old "docker-compose" command and changes it to the new "docker compose" command as it already been used in the documentation a few lines before.
=> fix: change old docker compose command

guide/invoicing/net-payment-term.mdx
In the Invoice `Net payment Term` doc, it says that no webhook is triggered when an invoice payment becomes overdue (after the net payment term).
However [this code](https://github.com/getlago/lago-api/blob/41a994c4ffc579462f1eceff6dc64d1d0f211818/app/jobs/clock/mark_invoices_as_payment_overdue_job.rb#L24) seems to indicate that the `invoice.payment_overdue` webhook message is sent. I assume this is just an overlook in the docs ?
=> Net payment term missing mention to `invoice.payment_overdue` webhook

guide/self-hosted/docker.mdx
This PR updates the self-hosted documentation to make sure that the `LAGO_RSA_PRIVATE_KEY` will not contains carriage return as it could cause issues with some configurations
Related to https://github.com/getlago/lago/issues/389
=> fix(self-hosted): Fix intialization of RSA private key

guide/payments/cashfree-payments.mdx, mint.json
Feels like the doc got a weird navigation behaviour on the `integrations` page. We directly land on Cashfree’s page instead of Integrations > Introduction
The mint.json was targeting wrong files.
=> doc(Integration): Fix navigation issue

docs.json, guide/migration/migration-to-v1.25.0.mdx
In this version and newer we need billing_entity_id and organization_id to be populated on fees. This guide explains what is needed to do it
=> Chore: Added guide to migrate to lago version 1.25.0

guide/billing_entities.mdx
Added a page in the guides about billing_entity. Didn't add the link to this page to the navigation in case we don't want this page to be visible yet
=> Feat(multientieis): add overview on billing entities without adding the link

guide/payments/stripe-integration.mdx, integrations/payments/stripe-integration.mdx
Adds instructions about the scope required for a [Stripe restricted API key](https://docs.stripe.com/keys-best-practices#limit-access).
=> doc(stripe): stripe restricted api key

api-reference/resources/locales.mdx
Portuguese (Brazil) `pt_BR` is now part of supported locales in the app.
=> misc: mention pt_BR as a newly supported document locale

guide/lago-self-hosted/docker.mdx
This PR updates the self-hosted documentation to make sure that people always start the application on the last released version rather than on the main branch as it could contains some inconsistencies
=> misc(docker): Checkout latest git tag
